### ISSUE TITLE
Cant add light bulb RGBCCT wifi using config flow

### ISSUE THREAD

**Issue by Koliadjun** [rospogrigio/localtuya-homeassistant#74] opened 2020-10-11 09:49 UTC
![2020-10-11 (5)](https://user-images.githubusercontent.com/14816869/95675434-e5faa580-0bbf-11eb-8715-ada10aef7f40.png)

It is fn unknown error occurred. See log for details.

Log
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:224
Integration: LocalTuya integration (documentation)
First occurred: 12:44:54 (1 occurrences)
Last logged: 12:44:54

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 235, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 171, in validate_input
    detected_dps = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 271, in detect_available_dps
    data = self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 244, in status
    return self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 239, in exchange
    return self.exchange(command, dps)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 224, in exchange
    data = s.recv(1024)
socket.timeout: timed out

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:273
Integration: LocalTuya integration (documentation)
First occurred: 12:44:54 (1 occurrences)
Last logged: 12:44:54

Failed to get status: timed out

**Comment by postlund** [comment] 2020-10-11 10:38
Duplicate of #63.

**Closed by postlund** 2020-10-11 10:38 UTC
